## Lab - 08
### 1928343 - Kapil Sharma
### Lab Question - 02

In [23]:
#Importing libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

In [12]:
df = pd.read_csv('caesarian.csv')
x = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [13]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.25, random_state=0)
print(x_train)
print(x_test)
print(y_train)
print(y_test)

[[36  1  1  2  0]
 [31  1  0  1  0]
 [19  1  0  1  0]
 [24  2  2  1  0]
 [25  2  0  1  0]
 [20  1  2  2  0]
 [22  1  2  2  0]
 [32  2  0  0  0]
 [27  2  0  1  0]
 [32  3  1  0  1]
 [32  3  0  1  1]
 [22  2  0  1  0]
 [27  2  0  1  1]
 [35  1  1  0  0]
 [32  1  0  2  1]
 [33  1  1  0  0]
 [21  1  0  0  0]
 [27  1  0  0  1]
 [36  1  0  1  0]
 [40  1  0  1  1]
 [22  1  0  1  0]
 [19  1  0  1  0]
 [26  2  0  1  0]
 [32  2  0  2  1]
 [27  2  1  1  0]
 [29  1  2  0  1]
 [29  2  0  1  1]
 [24  1  2  0  1]
 [26  2  1  1  1]
 [29  2  0  0  1]
 [20  1  0  2  1]
 [28  3  0  2  0]
 [37  3  0  1  1]
 [22  1  0  2  0]
 [25  1  2  0  0]
 [25  1  2  0  0]
 [26  1  1  0  0]
 [30  2  1  2  1]
 [25  1  0  1  0]
 [21  2  1  0  1]
 [26  1  1  1  0]
 [38  3  2  2  1]
 [28  2  0  1  0]
 [20  1  0  1  1]
 [18  1  0  1  0]
 [31  2  2  1  0]
 [26  1  0  1  0]
 [26  1  2  0  1]
 [35  2  0  1  0]
 [26  1  0  2  0]
 [23  1  1  1  0]
 [17  1  0  0  0]
 [33  1  1  1  0]
 [33  2  0  0  1]
 [27  1  1  1  0]
 [33  4  0

In [14]:
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
print(x_train)
print(x_test)

[[ 1.51901137 -0.77032889  0.53360851  1.46298045 -0.81649658]
 [ 0.6021031  -0.77032889 -0.74705191  0.04719292 -0.81649658]
 [-1.59847675 -0.77032889 -0.74705191  0.04719292 -0.81649658]
 [-0.68156848  0.51355259  1.81426893  0.04719292 -0.81649658]
 [-0.49818683  0.51355259 -0.74705191  0.04719292 -0.81649658]
 [-1.4150951  -0.77032889  1.81426893  1.46298045 -0.81649658]
 [-1.04833179 -0.77032889  1.81426893  1.46298045 -0.81649658]
 [ 0.78548475  0.51355259 -0.74705191 -1.36859462 -0.81649658]
 [-0.13142352  0.51355259 -0.74705191  0.04719292 -0.81649658]
 [ 0.78548475  1.79743407  0.53360851 -1.36859462  1.22474487]
 [ 0.78548475  1.79743407 -0.74705191  0.04719292  1.22474487]
 [-1.04833179  0.51355259 -0.74705191  0.04719292 -0.81649658]
 [-0.13142352  0.51355259 -0.74705191  0.04719292  1.22474487]
 [ 1.33562972 -0.77032889  0.53360851 -1.36859462 -0.81649658]
 [ 0.78548475 -0.77032889 -0.74705191  1.46298045  1.22474487]
 [ 0.96886641 -0.77032889  0.53360851 -1.36859462 -0.81

In [15]:
classifier = KNeighborsClassifier(n_neighbors = 5, metric ='minkowski', p =2)
classifier.fit(x_train,y_train)

KNeighborsClassifier()

In [16]:
print(classifier.predict(sc.transform([[26, 1, 0, 1, 0]])))

[0]


In [20]:
y_pred = classifier.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 1]]


In [22]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[9 1]
 [4 6]]


0.75