In [1]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('FoodTruck.csv')
df

Population    Profit
0       6.1101  17.59200
1       5.5277   9.13020
2       8.5186  13.66200
3       7.0032  11.85400
4       5.8598   6.82330
..         ...       ...
92      5.8707   7.20290
93      5.3054   1.98690
94      8.2934   0.14454
95     13.3940   9.05510
96      5.4369   0.61705

[97 rows x 2 columns]

In [3]:
df.shape

(97, 2)

In [5]:
features = df['Population'].values
features

array([ 6.1101,  5.5277,  8.5186,  7.0032,  5.8598,  8.3829,  7.4764,
        8.5781,  6.4862,  5.0546,  5.7107, 14.164 ,  5.734 ,  8.4084,
        5.6407,  5.3794,  6.3654,  5.1301,  6.4296,  7.0708,  6.1891,
       20.27  ,  5.4901,  6.3261,  5.5649, 18.945 , 12.828 , 10.957 ,
       13.176 , 22.203 ,  5.2524,  6.5894,  9.2482,  5.8918,  8.2111,
        7.9334,  8.0959,  5.6063, 12.836 ,  6.3534,  5.4069,  6.8825,
       11.708 ,  5.7737,  7.8247,  7.0931,  5.0702,  5.8014, 11.7   ,
        5.5416,  7.5402,  5.3077,  7.4239,  7.6031,  6.3328,  6.3589,
        6.2742,  5.6397,  9.3102,  9.4536,  8.8254,  5.1793, 21.279 ,
       14.908 , 18.959 ,  7.2182,  8.2951, 10.236 ,  5.4994, 20.341 ,
       10.136 ,  7.3345,  6.0062,  7.2259,  5.0269,  6.5479,  7.5386,
        5.0365, 10.274 ,  5.1077,  5.7292,  5.1884,  6.3557,  9.7687,
        6.5159,  8.5172,  9.1802,  6.002 ,  5.5204,  5.0594,  5.7077,
        7.6366,  5.8707,  5.3054,  8.2934, 13.394 ,  5.4369])

In [8]:
labels = df['Profit'].values
labels

array([17.592  ,  9.1302 , 13.662  , 11.854  ,  6.8233 , 11.886  ,
        4.3483 , 12.     ,  6.5987 ,  3.8166 ,  3.2522 , 15.505  ,
        3.1551 ,  7.2258 ,  0.71618,  3.5129 ,  5.3048 ,  0.56077,
        3.6518 ,  5.3893 ,  3.1386 , 21.767  ,  4.263  ,  5.1875 ,
        3.0825 , 22.638  , 13.501  ,  7.0467 , 14.692  , 24.147  ,
       -1.22   ,  5.9966 , 12.134  ,  1.8495 ,  6.5426 ,  4.5623 ,
        4.1164 ,  3.3928 , 10.117  ,  5.4974 ,  0.55657,  3.9115 ,
        5.3854 ,  2.4406 ,  6.7318 ,  1.0463 ,  5.1337 ,  1.844  ,
        8.0043 ,  1.0179 ,  6.7504 ,  1.8396 ,  4.2885 ,  4.9981 ,
        1.4233 , -1.4211 ,  2.4756 ,  4.6042 ,  3.9624 ,  5.4141 ,
        5.1694 , -0.74279, 17.929  , 12.054  , 17.054  ,  4.8852 ,
        5.7442 ,  7.7754 ,  1.0173 , 20.992  ,  6.6799 ,  4.0259 ,
        1.2784 ,  3.3411 , -2.6807 ,  0.29678,  3.8845 ,  5.7014 ,
        6.7526 ,  2.0576 ,  0.47953,  0.20421,  0.67861,  7.5435 ,
        5.3436 ,  4.2415 ,  6.7981 ,  0.92695,  0.152  ,  2.82

In [9]:
features_train, features_test, labels_train, labels_test = train_test_split(features, labels, test_size = 30, random_state = 41)

In [13]:
regressor = LinearRegression()
features_train = features_train.reshape(67,1)

In [14]:
regressor.fit(features_train, labels_train)

LinearRegression()

In [18]:
features_test = features_test.reshape(30,1)
final = regressor.predict(features_test)
final

array([ 2.27122518,  6.73787566,  2.82024924,  4.72099943,  1.83276353,
        1.91704666,  2.62729771,  3.10363941,  2.45825796,  7.43451356,
        5.69013698,  8.84116577,  6.81837078,  5.9547055 ,  4.79462879,
        2.38072222, 18.29697475,  2.8452264 ,  2.15107438,  2.54680259,
        2.97567585,  9.72069332,  2.9806476 ,  6.31788054,  3.48184809,
        3.36726093,  8.03266332,  2.405581  ,  6.02513873,  2.50726528])

In [19]:
pd.DataFrame(zip(final, labels_train))

0         1
0    2.271225  15.50500
1    6.737876   5.30480
2    2.820249  -2.68070
3    4.720999   1.01790
4    1.832764  24.14700
5    1.917047   0.61705
6    2.627298   3.51290
7    3.103639   3.34110
8    2.458258   5.34360
9    7.434514   5.38540
10   5.690137   3.91150
11   8.841166   3.81660
12   6.818371   0.71618
13   5.954706  17.92900
14   4.794629   7.77540
15   2.380722  10.11700
16  18.296975   3.25220
17   2.845226   6.59870
18   2.151074   1.84400
19   2.546803   0.20421
20   2.975676  21.76700
21   9.720693   5.99660
22   2.980648  -1.22000
23   6.317881   2.44060
24   3.481848   4.11640
25   3.367261   1.04630
26   8.032663   5.13370
27   2.405581   4.02590
28   6.025139   4.26300
29   2.507265   6.73180

In [21]:
regressor.score(features_train, labels_train)

0.78474532835774

In [25]:
regressor.predict([[3073000]])

array([3637664.99890389])